import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#30476a",
        "tertiary": "#43597e",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#466a71",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#d5e3ff",
        "background": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "primary-fixed-dim": "#94ccff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#a8cdd5",
        "tertiary-container": "#5b7297",
        "primary": "#005d90",
        "secondary-fixed": "#c3e9f1",
        "primary-fixed": "#cde5ff",
        "on-primary-fixed": "#001d32",
        "secondary": "#40646b",
        "error-container": "#ffdad6",
        "primary-container": "#0077b6",
        "inverse-primary": "#94ccff",
        "on-background": "#191c1e",
        "secondary-container": "#c3e9f1",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#b0c7f1",
        "surface-tint": "#006399",
        "on-primary-container": "#f3f7ff",
        "on-surface-variant": "#404850",
        "on-primary-fixed-variant": "#004b74",
        "on-tertiary-fixed": "#001b3c",
        "surface-dim": "#d8dadc",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#284c53",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#001f24",
        "outline": "#707881",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#ffffff",
        "outline-variant": "#bfc7d1",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#f5f6ff",
        "deep-navy": "#1D3557",
        "light-blue": "#CAF0F8",
        "light-blue-bg": "#CAF0F8",
        "whatsapp": "#25D366"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "md": "16px",
        "base": "4px",
        "gutter": "24px",
        "xl": "40px",
        "lg": "24px",
        "xs": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "container-max": "1280px",
        "section-padding": "120px"
      },
      fontFamily: {
        sans: ["var(--font-hanken-grotesk)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
        rajdhani: ["var(--font-rajdhani)", "sans-serif"],
        "body-md": ["var(--font-hanken-grotesk)", "sans-serif"],
        "title-md": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-lg-mobile": ["var(--font-hanken-grotesk)", "sans-serif"],
        "display-lg": ["var(--font-hanken-grotesk)", "sans-serif"],
        "label-caps": ["var(--font-jetbrains-mono)", "monospace"],
        "stats-num": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-md": ["var(--font-hanken-grotesk)", "sans-serif"],
        "headline-xl": ["var(--font-hanken-grotesk)", "sans-serif"],
        "body-lg": ["var(--font-hanken-grotesk)", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "stats-num": ["56px", { lineHeight: "1", fontWeight: "800" }]
      }
    },
  },
  plugins: [],
};

export default config;
